export const restaurants = [
  {
    info: {
      id: "378344",
      name: "Theobroma",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/27/7905cfb7-0067-4942-92cd-1898a81f69f4_378344.JPG",
      locality: "Banjara Hills",
      costForTwo: "₹400 for two",
      cuisines: ["Desserts"],
      avgRating: 4.5,
      sla: {
        deliveryTime: 49,
        lastMileTravel: 4.3,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "4.3 km",
      },
    },
  },
  {
    info: {
      id: "657474",
      name: "Burger King",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/18/ea422e81-79ea-4ffa-b56b-bc0dbc34520d_657474.jpg",
      locality: "R5 Chambers",
      costForTwo: "₹350 for two",
      cuisines: ["Burgers", "American"],
      avgRating: 4.1,
      sla: {
        deliveryTime: 44,
        lastMileTravel: 3.5,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "3.5 km",
      },
    },
  },
  {
    info: {
      id: "262087",
      name: "Imperial Multicuisine Restaurant",
      cloudinaryImageId: "rqlwvsmzcfxbg9u6ajgm",
      locality: "Banjara Hills",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
      avgRating: 4.3,
      sla: {
        deliveryTime: 46,
        lastMileTravel: 2.7,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "2.7 km",
      },
    },
  },
  {
    info: {
      id: "639526",
      name: "Dum Safar Biryani",
      cloudinaryImageId: "1154cffac2453eb0bf7fdda7e5ea1659",
      locality: "City Plaza",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Kebabs", "North Indian", "Barbecue"],
      avgRating: 4.0,
      sla: {
        deliveryTime: 54,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "6498",
      name: "Hotel Sandarshini",
      cloudinaryImageId: "9f5783b9975a73ec001560327065a01c",
      locality: "Masab Tank",
      costForTwo: "₹200 for two",
      cuisines: ["Chinese", "South Indian", "Juices"],
      avgRating: 4.6,
      sla: {
        deliveryTime: 41,
        lastMileTravel: 2.9,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "2.9 km",
      },
    },
  },
  {
    info: {
      id: "7203",
      name: "Taj Mahal-Abids",
      cloudinaryImageId: "8aa874a03b5bd0804b6781b1fd13f02d",
      locality: "Abids",
      costForTwo: "₹400 for two",
      cuisines: ["South Indian", "North Indian", "Biryani", "Snacks"],
      avgRating: 4.5,
      sla: {
        deliveryTime: 60,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "60-70 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "27739",
      name: "Cafe Niloufer Classic",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/2/19/b537f9cd-5a6a-45dd-b88a-167641488c06_27739.jpg",
      locality: "Oshiwara",
      costForTwo: "₹150 for two",
      cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
      avgRating: 4.7,
      sla: {
        deliveryTime: 50,
        lastMileTravel: 2.8,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "2.8 km",
      },
    },
  },
  {
    info: {
      id: "2535",
      name: "Agra Sweets Banjara",
      cloudinaryImageId: "ydsyhgg51xaxsrjbaxdv",
      locality: "Masab Tank",
      costForTwo: "₹250 for two",
      cuisines: ["Sweets", "Desserts", "Chaat", "Snacks", "Beverages"],
      avgRating: 4.5,
      sla: {
        deliveryTime: 47,
        lastMileTravel: 3.8,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "3.8 km",
      },
    },
  },
  {
    info: {
      id: "367769",
      name: "Lucky Restaurant",
      cloudinaryImageId: "qems028i3da5rxf81rbp",
      locality: "Banjara Hills",
      costForTwo: "₹300 for two",
      cuisines: ["Biryani", "Tandoor"],
      avgRating: 4.0,
      sla: {
        deliveryTime: 43,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "37103",
      name: "KFC",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/10/17/c7165489-d6fc-47b8-a68f-8b47312fe788_37103.JPG",
      locality: "Abids",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Fast Food", "Rolls & Wraps"],
      avgRating: 4.2,
      sla: {
        deliveryTime: 51,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "16158",
      name: "Royal Tiffin Centre",
      cloudinaryImageId: "xxvnkzmpgmbojcakxws4",
      locality: "Hanuman Tekdi",
      costForTwo: "₹150 for two",
      cuisines: ["South Indian"],
      avgRating: 4.1,
      sla: {
        deliveryTime: 59,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "55-65 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "9304",
      name: "Rayalaseema Ruchulu",
      cloudinaryImageId: "oqngjvi8wsc38wffxfa6",
      locality: "Lakdi-Ka-Pul",
      costForTwo: "₹450 for two",
      cuisines: ["South Indian", "Biryani", "Rayalaseema", "North Indian"],
      avgRating: 4.3,
      sla: {
        deliveryTime: 50,
        lastMileTravel: 2.9,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "2.9 km",
      },
    },
  },
  {
    info: {
      id: "10273",
      name: "Scoops Ice Cream",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/7/17/b5f3da6c-d909-4643-9c42-85d7e3b1d758_10273.JPG",
      locality: "Koti Main road",
      costForTwo: "₹200 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.6,
      sla: {
        deliveryTime: 51,
        lastMileTravel: 3.6,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "3.6 km",
      },
    },
  },
  {
    info: {
      id: "233055",
      name: "The Good Bowl",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/11/15/d154a250-4cd7-4530-b209-ddc09d952b14_233055.jpg",
      locality: "Beside Little Flower Primary school",
      costForTwo: "₹400 for two",
      cuisines: ["Biryani", "Pastas", "Punjabi", "Desserts", "Beverages"],
      avgRating: 4.1,
      sla: {
        deliveryTime: 58,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "55-65 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "185544",
      name: "NIC Ice Creams",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/7/8/cfbc3475-a332-4547-9266-e552b8189e89_185544.JPG",
      locality: "Khairatabad",
      costForTwo: "₹120 for two",
      cuisines: ["Desserts", "Ice Cream"],
      avgRating: 4.6,
      sla: {
        deliveryTime: 49,
        lastMileTravel: 4.1,
        serviceability: "SERVICEABLE",
        slaString: "45-50 mins",
        lastMileTravelString: "4.1 km",
      },
    },
  },
  {
    info: {
      id: "560732",
      name: "Natural Ice Cream",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/3/21/cee3277a-2b10-44c0-abe4-304c869bb29b_560732.jpg",
      locality: "Himayath Nagar",
      costForTwo: "₹150 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.7,
      sla: {
        deliveryTime: 50,
        lastMileTravel: 4.8,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "4.8 km",
      },
    },
  },
  {
    info: {
      id: "800052",
      name: "Quick Crave",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/2/6eadfee6-6c57-4f9c-a8c5-479ad0230166_800052.jpg",
      locality: "Beside Little Flower Primary school",
      costForTwo: "₹500 for two",
      cuisines: ["Pizzas", "Fast Food"],
      avgRating: 4.0,
      sla: {
        deliveryTime: 44,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "395279",
      name: "McDonald's Gourmet Burger Collection",
      cloudinaryImageId: "zqjiuzjclswtjkxrmvvn",
      locality: "Humayun Nagar",
      costForTwo: "₹600 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.5,
      sla: {
        deliveryTime: 49,
        lastMileTravel: 3.5,
        serviceability: "SERVICEABLE",
        slaString: "45-55 mins",
        lastMileTravelString: "3.5 km",
      },
    },
  },
  {
    info: {
      id: "575164",
      name: "Veg Darbar by Behrouz Biryani",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/9/9/65f8dfaa-053d-4892-b21c-b41138c5d320_575164.JPG",
      locality: "Beside Little Flower Primary school",
      costForTwo: "₹700 for two",
      cuisines: [
        "Biryani",
        "North Indian",
        "Kebabs",
        "Mughlai",
        "Lucknowi",
        "Hyderabadi",
        "Desserts",
        "Beverages",
      ],
      avgRating: 4.3,
      sla: {
        deliveryTime: 59,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "55-65 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
  {
    info: {
      id: "853135",
      name: "Go Zero Ice Creams & Desserts",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2025/6/24/ab797910-dcd5-4cb0-9e69-23acb74f2ea2_853135.JPG",
      locality: "Nampally",
      costForTwo: "₹150 for two",
      cuisines: ["Ice Cream", "Desserts", "Healthy Food"],
      avgRating: 3.9,
      sla: {
        deliveryTime: 52,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "50-60 mins",
        lastMileTravelString: "3.0 km",
      },
    },
  },
];
